version: "3.3"
services:
  skrman:
    image: ghcr.io/aiza2a/exloli-imgx:latest
    container_name: EXLOLI-IMGX
    volumes:
      - ./db.sqlite:/app/db.sqlite
      - ./db.text.json:/app/db.text.json
      - ./config.toml:/app/config.toml
    restart: unless-stopped
