name: Rust formatting

on:
  pull_request:
    branches: [master]
  push:
    branches: [master, maintenance/docs-ci-container, maintenance/stability-admin-update]

permissions:
  contents: read

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - name: Format source
        run: cargo fmt --all
